events {
    worker_connections 1024;
}

http {
    # DNS de Docker + DNS de Google para evitar problemas resolviendo dominios externos
    resolver 127.0.0.11 8.8.8.8 valid=5s;

    server {
        listen 8080;
        location /metrics {
            stub_status on;
            allow all;
        }
    }

    server {
        listen 80;

        # Ruta Primaria: Nodo Local
        location / {
            set $backend "http://ethereum-node:8545";
            proxy_pass $backend;
            
            # Intercepta errores y mándalos al fallback
            proxy_intercept_errors on;
            error_page 502 504 = @fallback;
        }

        # Ruta de Respaldo: PublicNode (Directo, sin upstream)
        location @fallback {
            proxy_pass https://ethereum-rpc.publicnode.com;
            
            # Cabeceras estrictas obligatorias
            proxy_set_header Host ethereum-rpc.publicnode.com;
            proxy_ssl_server_name on;
        }
    }
}
