events {
    worker_connections 1024;
}

http {
    # Usamos el servidor DNS interno de Docker (127.0.0.11)
    resolver 127.0.0.11 valid=5s;

    server {
        listen 80;

        location / {
            # Definimos el destino como variable para que Nginx no colapse si está apagado al inicio
            set $backend "http://ethereum-node:8545";
            proxy_pass $backend;
            
            # Si el destino local no responde, manda al paciente a urgencias
            proxy_intercept_errors on;
            error_page 502 504 = @fallback;
        }

        location @fallback {
            # Nodo en la nube
            set $backup_node "https://cloudflare-eth.com";
            proxy_pass $backup_node;
            
            # Gafetes de seguridad
            proxy_ssl_server_name on;
            proxy_ssl_name cloudflare-eth.com;
            
            proxy_set_header Host cloudflare-eth.com;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Content-Type application/json;
            proxy_set_header Accept application/json;
        }
    }
}
